# This is a TOML file containing parameters for this contract

[meta]
# This hash must match the hash of the local template.md file. DO NOT MAKE CHANGES TO THIS HASH.
template = "5E43F71626F4D7F2F79B3650E14295760EA190DB51DF6EC9EFF4EF145E2B255E"

[var]
date = ""
consultant = ""
schedule = ""
start-date = ""
email = ""


[exhibit]
services = ""
compensation = ""
expenses = ""


[sign]
image = ""
company-signer = ""

